import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/app.js';
Object.assign(process.env,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_test',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',LINE_CHANNEL_ID:'12345',LIFF_ID:'12345-test'});
async function call(body,token=''){let code=200,data;const headers={};const res={setHeader(k,v){headers[k]=v;},status(n){code=n;return this;},json(d){data=d;return this;}};await handler({method:'POST',body,headers:{host:'example.vercel.app','x-member-app':'1',...(token?{authorization:'Bearer '+token}:{})}},res);return {code,data,headers};}
function response(data,status=200){return new Response(JSON.stringify(data),{status});}
test('no admin action without authentication',async()=>{assert.equal((await call({action:'sale'})).code,401);});
test('forged LINE token rejected',async()=>{global.fetch=async()=>response({error:'invalid'},400);assert.equal((await call({action:'me'},'forged')).code,401);});
test('verified LINE subject only; two upstream calls; customer never receives transaction details',async()=>{let step=0;global.fetch=async(url,opts)=>{step++;if(step===1){assert.equal(new URLSearchParams(opts.body).get('client_id'),'12345');return response({sub:'LINE_A',name:'A'});}assert.match(url,/line_page_v2$/);const b=JSON.parse(opts.body);assert.equal(b.p_line,'LINE_A');assert.equal(b.p_member,undefined);return response({member:{id:'member-A',display_name:'A',phone:'secret-phone',note:'private'},total:1000,points:100,visits:1,transactions:[{items:'secret',paid:1000}],point_days:[{day:'2026-09-09',earned:100,paid:1000,items:['hidden']}],next_day:null});};const d=await call({action:'me',member_id:'member-B'},'valid');assert.equal(step,2);assert.deepEqual(d.data,{member:{id:'member-A',display_name:'A'},total:1000,points:100,visits:1,point_days:[{day:'2026-09-09',earned:100}],next_day:null});assert.equal(d.headers['Cache-Control'],'no-store');});
test('authenticated non-admin forbidden by database role check',async()=>{let n=0;global.fetch=async()=>++n===1?response({id:'nonadmin'}):response({code:'42501',message:'沒有管理權限'},403);assert.equal((await call({action:'report',month:'2026-09'},'token')).code,403);});
test('client cannot override the actor or force preview to commit',async()=>{let n=0;global.fetch=async(url,opts)=>{if(++n===1)return response({id:'real-admin'});const b=JSON.parse(opts.body);assert.equal(b.p_actor,'real-admin');assert.equal(b.p_dry,true);return response({dry_run:true});};assert.equal((await call({action:'import',p_actor:'fake',rows:[],dry_run:'false'},'token')).code,200);});
test('configuration does not expose keys',async()=>{const d=await call({action:'config'});assert.equal(JSON.stringify(d).includes('sb_secret'),false);assert.equal(JSON.stringify(d).includes('sb_publishable'),false);});
test('cross-origin writes rejected',async()=>{let code;await handler({method:'POST',headers:{host:'example.vercel.app',origin:'https://evil.example'},body:{action:'sale'}},{setHeader(){},status(c){code=c;return this;},json(){}});assert.equal(code,403);});
test('missing migration produces actionable error',async()=>{let n=0;global.fetch=async()=>++n===1?response({id:'admin'}):response({code:'PGRST202'},404);const r=await call({action:'report',month:'2026-09'},'token');assert.equal(r.code,503);assert.match(r.data.error,/10_repair_member_db_rpc.sql/);});
