process.on('uncaughtException',e=>{console.error(JSON.stringify({message:e.message,code:e.code,position:e.position,where:e.where,detail:e.detail,actual:e.actual,expected:e.expected}));process.exit(1);});
// Optional PostgreSQL-WASM integration suite. Install @electric-sql/pglite in a temporary test directory.
import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();let checks=0;
async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
async function rpc(name,args){const values=Object.values(args);const {rows}=await db.query(`select public.${name}(${values.map((_,i)=>'$'+(i+1)).join(',')}) as d`,values);return rows[0].d;}
const admin='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',nonadmin='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
const sale=(mid,gross,redeemed,at,name='商品')=>({id:crypto.randomUUID(),member_id:mid,gross,redeemed,occurred_at:at,note:'',items:[{name,qty:1,price:gross}],external_id:null});
const write=data=>rpc('admin_write_v2',{actor:admin,action:'sale',data});
await db.exec('create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key,email text);');
await db.exec(readFileSync('sql/01_setup.sql','utf8'));
await db.query('insert into auth.users values ($1,$2),($3,$4)',[admin,'admin@example.com',nonadmin,'user@example.com']);await db.query('insert into public.admins values ($1)',[admin]);
await db.query("insert into members(id,line_id,display_name,note) values ($1,'LINE_A','會員 A','秘密'),($2,'LINE_B','會員 B','秘密')",[a,b]);
const legacy=sale(a,200,0,'2025-08-01T02:00:00Z');await rpc('admin_action',{actor:admin,action:'sale',data:legacy});
await db.exec(readFileSync('sql/04_upgrade_v2.sql','utf8'));
await check('migration preserves old members and transactions and can repeat',async()=>{await db.exec(readFileSync('sql/04_upgrade_v2.sql','utf8'));const d=await rpc('member_page_v2',{mid:a});assert.equal(d.total,200);assert.deepEqual(d.transactions[0].items,[]);});
const first=sale(a,1000,0,'2025-09-01T16:30:00Z'),second=sale(a,500,100,'2025-09-01T17:30:00Z'),third=sale(b,199,0,'2025-09-01T02:00:00Z');await write(first);await write(second);await write(third);
await check('Taipei month, daily totals, cashback vs redemption and frequency are correct',async()=>{const d=await rpc('admin_report_v2',{actor:admin,month:'2025-09'});assert.equal(d.current.paid,1599);assert.equal(d.current.earned,150);assert.equal(d.current.redeemed,100);assert.equal(d.current.visits,3);assert.equal(d.current.customers,2);assert.equal(d.previous.paid,200);assert.equal(d.days.length,30);assert.equal(d.days[1].earned,140);assert.equal(d.days[2].paid,0);assert.equal(d.frequency[0].value,1);assert.equal(d.frequency[1].value,1);});
await check('customers receive only aggregated point days, not transaction details',async()=>{const d=await rpc('line_page_v2',{line:'LINE_A',name:'不覆蓋'});assert.equal(d.points,60);assert.equal(d.total,1600);assert.equal(d.member.display_name,'會員 A');assert.deepEqual(d.point_days[0],{day:'2025-09-02',earned:140});assert.equal(d.transactions,undefined);assert.deepEqual(Object.keys(d.member).sort(),['display_name','id']);});
await check('customer comparison includes amount and visit deltas',async()=>{const d=await rpc('admin_compare_v2',{actor:admin,month:'2025-09'});const x=d.rows.find(x=>x.id===a);assert.equal(x.paid,1400);assert.equal(x.previous_paid,200);assert.equal(x.paid_diff,1200);assert.equal(x.visits_diff,1);});
await check('repeated order is idempotent and content conflict rejected',async()=>{assert.equal((await write(first)).duplicate,true);await assert.rejects(()=>write({...first,note:'different'}),/內容不同/);});
await check('invalid items and overspending fail',async()=>{await assert.rejects(()=>write({...sale(a,100,0,'2025-09-03T02:00:00Z'),items:[{name:'殼',qty:1,price:99}]}),/合計/);await assert.rejects(()=>write(sale(a,100,90,'2025-09-03T02:00:00Z')),/餘額不足/);});
await check('void cannot make balance negative; reverse redemption then rewards',async()=>{await assert.rejects(()=>rpc('admin_write_v2',{actor:admin,action:'void',data:{member_id:a,id:first.id,reason:'test'}}),/已被使用/);await rpc('admin_write_v2',{actor:admin,action:'void',data:{member_id:a,id:second.id,reason:'test'}});const d=await rpc('line_page_v2',{line:'LINE_A',name:'A'});assert.equal(d.points,120);assert.equal(d.point_days[0].earned,100);});
await check('old items can be filled without changing amount; audit is preserved',async()=>{await rpc('admin_write_v2',{actor:admin,action:'items',data:{member_id:a,id:legacy.id,items:[{name:'舊商品',qty:2,price:100}]}});const d=await rpc('admin_detail_v2',{actor:admin,mid:a});assert.equal(d.total,1200);assert.equal(d.member.note,'秘密');assert.ok(d.transactions.some(x=>x.id===legacy.id&&x.items.length===1));});
const imports=[{...sale(a,100,0,'2025-09-03T02:00:00Z'),external_id:'IMPORT-001'},{...sale(b,200,0,'2025-09-03T03:00:00Z'),external_id:'IMPORT-002'}];
await check('import preview truly rolls back, including audit; commit and retry are safe',async()=>{const before=(await db.query('select count(*) n from audit')).rows[0].n;const d=await rpc('admin_import_v2',{actor:admin,rows:imports,dry:true});assert.equal(d.created,2);assert.equal((await db.query('select count(*) n from audit')).rows[0].n,before);assert.equal((await db.query("select count(*) n from transactions where external_id like 'IMPORT-%'")).rows[0].n,0);assert.equal((await rpc('admin_import_v2',{actor:admin,rows:imports,dry:false})).created,2);assert.equal((await rpc('admin_import_v2',{actor:admin,rows:imports,dry:false})).duplicates,2);});
await check('one failed imported order rolls back the whole batch',async()=>{const rows=[{...sale(a,100,0,'2025-09-04T02:00:00Z'),external_id:'FAIL-1'},{...sale(a,999,999,'2025-09-04T03:00:00Z'),external_id:'FAIL-2'}];await assert.rejects(()=>rpc('admin_import_v2',{actor:admin,rows,dry:false}),/餘額不足/);assert.equal((await db.query("select count(*) n from transactions where external_id like 'FAIL-%'")).rows[0].n,0);});
await check('non-admin and anonymous DB users cannot read admin or customer RPCs',async()=>{await assert.rejects(()=>rpc('admin_report_v2',{actor:nonadmin,month:'2025-09'}),/沒有管理權限/);await db.exec('set role anon');await assert.rejects(()=>db.query('select * from public.transactions'),/permission denied/);await assert.rejects(()=>rpc('line_page_v2',{line:'LINE_A',name:'A'}),/permission denied/);await db.exec('reset role');});
await check('member and export keyset pages contain no missing or repeated rows',async()=>{for(let i=0;i<205;i++)await write(sale(b,100,0,new Date(Date.UTC(2025,8,5,0,i)).toISOString()));let cursor=null,ids=[];do{const d=await rpc('admin_export_v2',{actor:admin,month:'2025-09',cursor});ids.push(...d.rows.map(r=>r.id));cursor=d.next;}while(cursor);assert.equal(ids.length,new Set(ids).size);assert.equal(ids.length,(await db.query("select count(*) n from transactions where occurred_at>='2025-08-31T16:00:00Z' and occurred_at<'2025-09-30T16:00:00Z'")).rows[0].n);let mcursor=null,mids=[];do{const d=await rpc('member_page_v2',{mid:b,cursor:mcursor,size:20,summary:true});mids.push(...d.transactions.map(t=>t.id));mcursor=d.next;}while(mcursor);assert.equal(mids.length,new Set(mids).size);assert.equal(mids.length,207);});
await check('daily point pages are chronological, independent of transaction count',async()=>{for(let i=1;i<=25;i++)await write(sale(a,100,0,new Date(Date.UTC(2025,9,i)).toISOString()));const first=await rpc('line_page_v2',{line:'LINE_A',name:'A'});assert.equal(first.point_days.length,20);assert.ok(first.next_day);const second=await rpc('line_page_v2',{line:'LINE_A',name:'A',cursor:{day:first.next_day}});assert.ok(second.point_days.every(d=>d.day<first.next_day));const all=[...first.point_days,...second.point_days].map(d=>d.day);assert.equal(new Set(all).size,all.length);});
await check('empty month and invalid month are handled',async()=>{const d=await rpc('admin_report_v2',{actor:admin,month:'2024-02'});assert.equal(d.days.length,29);assert.equal(d.current.paid,0);assert.equal(d.current.average,0);await assert.rejects(()=>rpc('admin_report_v2',{actor:admin,month:'2025-13'}),/格式/);});
await check('copy-and-paste Supabase acceptance script runs and rolls back',async()=>{await db.exec(readFileSync('sql/05_verify_v2_rollback.sql','utf8'));});
console.log(`PASS ${checks} database integration scenarios`);await db.close();
