process.on('uncaughtException',e=>{console.error(JSON.stringify({message:e.message,code:e.code,where:e.where,actual:e.actual,expected:e.expected}));process.exit(1);});
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {wrapBackup,readBackup,restoreSQL} from '../public/backup.js';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',mid='11111111-1111-4111-8111-111111111111';
async function setup(d,auth=true){await d.exec('create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text);');for(const name of ['01_setup.sql','04_upgrade_v2.sql','06_upgrade_v3.sql'])await d.exec(readFileSync('sql/'+name,'utf8'));if(auth)await d.query('insert into auth.users values ($1,$2)',[actor,'admin@example.com']);}
const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) d`,args)).rows[0].d;
let n=0;async function check(name,fn){await fn();console.log('PASS '+name);n++;}
await setup(db);await db.query('insert into admins values ($1)',[actor]);await db.query("insert into members(id,line_id,display_name) values ($1,'LINE-ONE','測試會員')",[mid]);
const sale={id:crypto.randomUUID(),member_id:mid,gross:1000,redeemed:0,items:[{name:"殼'; drop table members; --",qty:1,price:1000}],note:'反斜線 \\ 與單引號 \u0027',occurred_at:'2025-09-01T01:00:00Z'};
await rpc('admin_write_v2',[actor,'sale',sale]);
await check('additive migration can repeat and preserves customer privacy',async()=>{await db.exec(readFileSync('sql/06_upgrade_v3.sql','utf8'));const d=await rpc('line_page_v2',['LINE-ONE','A']);assert.equal(d.points,50);assert.equal(d.transactions,undefined);});
await check('historical full and same-period reports agree',async()=>{const a=await rpc('admin_report_v3',[actor,'2025-09','same']);const b=await rpc('admin_report_v3',[actor,'2025-09','full']);assert.deepEqual(a.current,b.current);assert.equal(a.current.paid,1000);assert.equal(a.days.length,30);});
await check('current comparison excludes prior-month later dates',async()=>{const {rows:[{month,today}]}=await db.query("select to_char(now() at time zone 'Asia/Taipei','YYYY-MM') as month,(now() at time zone 'Asia/Taipei')::date::text today");const {rows:[bounds]}=await db.query('select * from period_bounds_v3($1,$2)',[month,'same']);assert.equal(new Date(bounds.end_at).toISOString().slice(0,10),today);assert.ok(new Date(bounds.previous_end)<=new Date(bounds.start_at));const d=await rpc('admin_report_v3',[actor,month,'same']);assert.equal(d.days.length,Number(today.slice(-2)));const cmp=await rpc('admin_compare_v3',[actor,month,0,'paid','same']);assert.ok(Array.isArray(cmp.rows));});
await check('point ledger matches balance; void reversal preserves history',async()=>{let d=await rpc('admin_operations_v3',[actor,'reconcile',{}]);assert.equal(d.total_points,50);assert.equal(d.difference_count,0);let l=await rpc('admin_operations_v3',[actor,'ledger',{member_id:mid}]);assert.equal(l.rows[0].balance,50);await rpc('admin_write_v2',[actor,'void',{member_id:mid,id:sale.id,reason:'測試退回'}]);l=await rpc('admin_operations_v3',[actor,'ledger',{member_id:mid}]);assert.equal(l.rows[0].earned,-50);assert.equal(l.rows[0].balance,0);assert.equal(l.rows.length,2);});
await check('reconciliation detects direct database changes with missing audit',async()=>{await db.query("update transactions set voided_at=null,voided_by=null,void_reason=null where id=$1",[sale.id]);const d=await rpc('admin_operations_v3',[actor,'reconcile',{}]);assert.equal(d.difference_count,1);assert.equal(d.rows[0].difference,50);await db.query('update transactions set voided_at=now(),voided_by=$1 where id=$2',[actor,sale.id]);});
await check('nonadmin and anon cannot read backup, ledger, audit or reports',async()=>{for(const action of ['backup','ledger','audit','reconcile','health'])await assert.rejects(()=>rpc('admin_operations_v3',['bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',action,{}]),/沒有管理權限/);await db.exec('set role anon');await assert.rejects(()=>rpc('admin_operations_v3',[actor,'backup',{}]),/permission denied/);await db.exec('reset role');});
const snapshot=await rpc('admin_operations_v3',[actor,'backup',{}]);
await check('backup checksum roundtrip and tampering detection',async()=>{const doc=await wrapBackup(structuredClone(snapshot));assert.deepEqual(await readBackup(JSON.stringify(doc)),snapshot);doc.payload.members[0].display_name='changed';await assert.rejects(()=>readBackup(JSON.stringify(doc)),/校驗碼/);});
await check('restore refuses existing business data',async()=>{await assert.rejects(()=>db.exec(restoreSQL(snapshot,true)),/不是空/);await db.exec('rollback');assert.equal((await db.query('select count(*) n from members')).rows[0].n,1);});
const recovery=new PGlite();await setup(recovery,false);
await check('restore refuses missing original Auth accounts',async()=>{await assert.rejects(()=>recovery.exec(restoreSQL(snapshot,true)),/Auth UUID/);await recovery.exec('rollback');await recovery.query('insert into auth.users values ($1,$2)',[actor,'admin@example.com']);});
await check('restore rehearsal validates but leaves no business data',async()=>{await recovery.exec(restoreSQL(snapshot,true));assert.equal((await recovery.query('select count(*) n from members')).rows[0].n,0);});
await check('committed restore preserves exact records and handles quotes safely',async()=>{await recovery.exec(restoreSQL(snapshot,false));for(const table of ['members','transactions','audit'])assert.deepEqual((await recovery.query('select * from '+table+' order by id')).rows,(await db.query('select * from '+table+' order by id')).rows);assert.equal((await recovery.query("select nextval(pg_get_serial_sequence('public.audit','id')) n")).rows[0].n,3);});
await check('copy-paste V3 acceptance script rolls back',async()=>{await db.exec(readFileSync('sql/07_verify_v3_rollback.sql','utf8'));assert.equal((await db.query('select count(*) n from members')).rows[0].n,1);});
console.log(`PASS ${n} V3 database/restore scenarios`);await db.close();await recovery.close();
