import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/app.js';
Object.assign(process.env,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_private',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',LINE_CHANNEL_ID:'12345'});
async function run(){let code=200,data;const res={setHeader(){},status(c){code=c;return this;},json(d){data=d;return this;}};await handler({method:'POST',headers:{host:'site.example','x-member-app':'1',authorization:'Bearer valid'},body:{action:'me'}},res);assert.ok(!JSON.stringify(data).includes('sb_secret_private'));return {code,data};}
function mockDB(status,data){let n=0;global.fetch=async()=>new Response(JSON.stringify(++n===1?{sub:'LINE_A',name:'A'}:data),{status:n===1?200:status});}
test('wrong backend key is actionable without exposing key',async()=>{mockDB(401,{message:'Invalid API key'});assert.equal((await run()).data.code,'DB-KEY');});
test('database grant error differs from admin membership rejection',async()=>{mockDB(403,{code:'42501',message:'permission denied for function line_page_v2'});const d=await run();assert.equal(d.code,503);assert.equal(d.data.code,'DB-PERM');});
test('a publishable key cannot be silently used as server secret',async()=>{process.env.SUPABASE_SECRET_KEY='sb_publishable_wrong';mockDB(200,{});assert.equal((await run()).data.code,'CFG-KEY');process.env.SUPABASE_SECRET_KEY='sb_secret_private';});
test('URL with rest path is rejected before DB call',async()=>{process.env.SUPABASE_URL='https://example.supabase.co/rest/v1';mockDB(200,{});assert.equal((await run()).data.code,'CFG-URL');process.env.SUPABASE_URL='https://example.supabase.co';});
test('network failure has safe retry code',async()=>{let n=0;global.fetch=async()=>{if(++n===1)return new Response(JSON.stringify({sub:'A'}));throw Error('sensitive internal hostname');};const d=await run();assert.equal(d.data.code,'DB-NET');assert.ok(!d.data.error.includes('hostname'));});
