import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/app.js';
Object.assign(process.env,{SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_test',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test'});
const response=(d,status=200)=>new Response(JSON.stringify(d),{status});
async function call(body,cookie='',extra={}){let code=200,data;const headers={};const res={setHeader(k,v){headers[k]=v;},status(n){code=n;return this;},json(d){data=d;return this;}};await handler({method:'POST',body,headers:{host:'shop.vercel.app','x-member-app':'1',cookie,...extra}},res);return {code,data,headers};}
test('login issues Secure HttpOnly cookies without exposing tokens in JSON',async()=>{let n=0;global.fetch=async()=>{n++;if(n===1)return response({access_token:'access-secret',refresh_token:'refresh-secret'});if(n===2)return response({id:'admin'});return response(null);};const r=await call({action:'login',email:'a@b.com',password:'password'});assert.equal(r.code,200);assert.deepEqual(r.data,{authenticated:true});assert.equal(r.headers['Set-Cookie'].length,2);for(const c of r.headers['Set-Cookie'])assert.match(c,/Path=\/; HttpOnly; Secure; SameSite=Lax$/);});
test('page reload restores session from cookie with no password or bearer',async()=>{global.fetch=async(url,opts)=>url.includes('/auth/v1/user')?(assert.equal(opts.headers.Authorization,'Bearer existing'),response({id:'admin'})):response(null);const r=await call({action:'session'},'__Host-mp_access=existing; __Host-mp_refresh=renew');assert.equal(r.data.authenticated,true);assert.equal(r.headers['Set-Cookie'],undefined);});
test('expired access is refreshed and cookies rotate after role recheck',async()=>{let n=0;global.fetch=async(url,opts)=>{n++;if(n===1)return response({},401);if(n===2){assert.match(url,/grant_type=refresh_token/);assert.deepEqual(JSON.parse(opts.body),{refresh_token:'refresh-old'});return response({access_token:'access-new',refresh_token:'refresh-new'});}if(n===3)return response({id:'admin'});return response(null);};const r=await call({action:'session'},'__Host-mp_access=expired; __Host-mp_refresh=refresh-old');assert.equal(r.code,200);assert.match(r.headers['Set-Cookie'][0],/access-new/);assert.match(r.headers['Set-Cookie'][1],/refresh-new/);assert.equal(n,4);});
test('revoked refresh clears cookies and requests login',async()=>{global.fetch=async()=>response({},400);const r=await call({action:'session'},'__Host-mp_refresh=revoked');assert.equal(r.code,401);assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')));});
test('database role removal blocks session restoration and clears cookies',async()=>{let n=0;global.fetch=async()=>++n===1?response({id:'removed-admin'}):response({code:'42501'},403);const r=await call({action:'session'},'__Host-mp_access=existing; __Host-mp_refresh=renew');assert.equal(r.code,403);assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')));});
test('logout clears browser cookies even when remote signout is unavailable',async()=>{global.fetch=async()=>{throw Error('offline');};const r=await call({action:'logout'},'__Host-mp_access=existing; __Host-mp_refresh=renew');assert.equal(r.code,200);assert.deepEqual(r.data,{authenticated:false,revoked:false});assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')));});
test('cross-site and simple form requests cannot use cookies or clear a session',async()=>{for(const extra of [{origin:'https://evil.example'},{'x-member-app':undefined}]){const r=await call({action:'logout'},'__Host-mp_access=existing',extra);assert.equal(r.code,403);assert.equal(r.headers['Set-Cookie'],undefined);}});
test('temporary Auth failure preserves cookies instead of logging the user out',async()=>{global.fetch=async()=>response({},503);const r=await call({action:'session'},'__Host-mp_access=existing; __Host-mp_refresh=renew');assert.equal(r.code,503);assert.equal(r.headers['Set-Cookie'],undefined);});
