begin;
drop function if exists public.admin_catalog_v39(uuid,text,jsonb);
create or replace function public.admin_health_v39(p_actor uuid) returns jsonb language plpgsql security definer set search_path=public as $$ begin perform require_admin_v2(p_actor); return jsonb_build_object('schema_version','3.9.1','checked_at',now(),'custom_orders_open',(select count(*) from custom_orders where not paid_in_full)); end $$;
create or replace function public.admin_backup_v39(p_actor uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare result jsonb; begin perform require_admin_v2(p_actor); lock table admins,members,transactions,audit,staff_options,custom_orders in share mode; select jsonb_build_object('format','line-member-business','version',4,'created_at',now(),'admins',(select coalesce(jsonb_agg(to_jsonb(t) order by user_id),'[]'::jsonb) from admins t),'members',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from members t),'transactions',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from transactions t),'audit',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from audit t),'staff_options',(select coalesce(jsonb_agg(to_jsonb(t) order by name),'[]'::jsonb) from staff_options t),'custom_orders',(select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) from custom_orders t),'points',(select coalesce(sum(earned-redeemed),0) from transactions where voided_at is null)) into result; if octet_length(result::text)>3000000 then raise exception '資料超過網頁備份容量，請依手冊使用資料庫備份'; end if; return result; end $$;
revoke all on function public.admin_health_v39(uuid) from public,anon,authenticated; grant execute on function public.admin_health_v39(uuid) to service_role;
revoke all on function public.admin_backup_v39(uuid) from public,anon,authenticated; grant execute on function public.admin_backup_v39(uuid) to service_role;
drop table if exists public.products;
notify pgrst, 'reload schema';
commit;
